[package]
    authors       = ["Naruyoko", "Rhelvetican", "baltdev"]
    categories    = ["no-std"]
    description   = "Stores numbers up to 10{N}9e15."
    documentation = "https://docs.rs/omeganum"
    edition       = "2021"
    keywords      = ["bignum", "math", "no-std", "port"]
    license       = "MIT"
    name          = "omeganum"
    repository    = "https://github.com/balt-dev/omeganum"
    rust-version  = "1.81.0"
    version       = "1.0.1"

[dependencies]
    libm       = { version = "0.2", optional = true }
    num-traits = "0.2"
    serde      = { version = "1", optional = true, features = ["serde_derive"] }

[features]
    default       = ["std"]
    error_in_core = []
    f16           = []
    libm          = ["dep:libm", "num-traits/libm"]
    serde         = ["dep:serde", "std"]
    std           = []

